export const privacySections = [
  { title: "Information handled by Friday", paragraphs: ["The Friday desktop application is designed to be local-first. Conversation history, memory, project data, generated media, settings, credentials, and permission rules are stored in the application data on your computer. Friday does not require an online account for these features.", "When you configure an AI, search, media, messaging, or other provider, Friday sends the information needed for the action directly to the provider you select. That provider's privacy policy and terms apply to its processing. Review each provider's settings before sending sensitive information."] },
  { title: "Website information", paragraphs: ["The website does not intentionally collect conversation content, application data, or provider credentials. Hosting infrastructure may process basic technical information such as an IP address, browser type, request time, and requested URL in server or security logs, according to the hosting provider's policies.", "The website links to third-party services, including GitHub, Product Hunt, social networks, and release downloads. Those services operate independently and may collect information under their own policies."] },
  { title: "Your choices and responsibilities", paragraphs: ["You choose which providers to connect, which folders to make available, which channels to enable, and which actions to approve. You can remove locally stored application data, revoke provider credentials, or disconnect an integration using the relevant application or provider controls.", "Keep your computer, backups, provider keys, and connected services secure. Do not send personal or confidential information to a provider unless you understand how it processes it."] },
  { title: "Children", paragraphs: ["Friday is not directed to children under 13, and we do not knowingly collect personal information from children through this website."] },
  { title: "Contact", paragraphs: ["For privacy questions, contact Harald Bregu at harald.bregu@gmail.com. This notice may be updated when the website or application changes; the date above identifies the latest revision."] },
];

export const termsSections = [
  { title: "Acceptance", paragraphs: ["By using the Friday website or desktop application, you accept these Terms of Service. If you do not accept them, do not use the website or application."] },
  { title: "Using the service", paragraphs: ["Friday is a desktop tool that can read and edit files, run commands, use online services, and generate content. You are responsible for the instructions you provide, the files and folders you make available, the providers and integrations you connect, and the actions you approve.", "Use Friday in compliance with applicable laws and third-party terms. Do not use Friday for illegal activity, to compromise systems or accounts, or to process data without authorization."] },
  { title: "Providers and third-party services", paragraphs: ["Friday can connect to AI providers, search services, messaging channels, MCP servers, and other services you choose. These services are independent from Friday; you are responsible for credentials, costs, permissions, and compliance with their terms and policies."] },
  { title: "No warranty", paragraphs: ["Friday is provided as-is and as available. Generated responses, tool actions, and produced content may contain errors; verify results before using or sharing them. To the extent permitted by law, Harald Bregu does not warrant that the service will always be available, accurate, or error-free."] },
  { title: "Changes and contact", paragraphs: ["These terms may be updated when the website or application changes. The latest revision date will be shown on this page. For questions, contact Harald Bregu at harald.bregu@gmail.com."] },
];
